# Generated by Django 2.0.1 on 2018-01-22 22:48

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\nmb\\Documents\\School\\Udemy\\DigitalMarketplace\\static_cdn\\protected'), upload_to=products.models.user_directory_path),
        ),
    ]
